### ISSUE TITLE
compact stage tries to compact system collections

### ISSUE THREAD

**Issue by axinojolais** [juju/mgopurge#21]
Hi,

Running mgopurge v1.6, I got the following : 
`2017-10-26 12:24:26 ERROR failed stage compact: while compacting system.profile: not authorized on juju to execute command { compact: "system.profile", force: 1 }`

I guess mgopurge shouldn't try to do that.

**Comment by jameinel** [comment]
I wonder if this is a case of running as a machine agent vs running as admin.
As mgopurge hasn't changed in this area AFAICT.
There are several other places where we explicitly filter out system.* tables, we could probably just do that for compact as well.

**Comment by axinojolais** [comment]
FWIW, mgopurge ran with user "machine-2"

**Comment by axinojolais** [comment]
This bug hit me again today, it would be nice to have a release with the fix.

Also, I _think_ we may have tweaked the mongodb users and given them more permissions than juju does by default, for monitoring purposes. This could explain why we're seeing this and you're not.

**Comment by axinojolais** [comment]
How to purge the remaining collections : 
```
use logs
db.getCollectionNames().forEach(function(uuid) {print(uuid); db.runCommand ( { compact: uuid , force: 1 } ) })
use juju
["toolsmetadata", "txns", "txns.log", "txns.prune", "txns.stash", "units", "upgradeInfo", "userLastLogin", "usermodelname", "users", "volumeattachments", "volumes"].forEach(function(uuid) {print(uuid); db.runCommand ( { compact: uuid , force: 1 } ) })
```
